"""
Django settings for project project.

Generated by 'django-admin startproject' using Django 4.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

# flake8: noqa
from .environment import *  # isort:skip
from .installed_apps import *  # isort:skip
from .middlewares import *  # isort:skip
from .templates import *
from .assets import *
from .databases import *
from .security import *
from .i18n import *
from .messages import *
from .debug_toolbar import *  # isort:skip
